# Generated by Django 2.2.7 on 2019-11-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('code_2', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=52)),
                ('continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica'), ('South America', 'South America')], max_length=13)),
                ('region', models.CharField(default=('Asia', 'Asia'), max_length=26)),
                ('surface_area', models.FloatField(default=0.0, max_length=12)),
                ('indep_year', models.SmallIntegerField(default=None, null=True)),
                ('population', models.IntegerField(default=0)),
                ('life_expectancy', models.FloatField(default=None, max_length=4, null=True)),
                ('GNP', models.FloatField(default=None, max_length=12, null=True)),
                ('GNP_old', models.FloatField(default=None, max_length=12, null=True)),
                ('local_name', models.CharField(max_length=45)),
                ('government_form', models.CharField(max_length=45)),
                ('head_of_state', models.CharField(default=None, max_length=60, null=True)),
                ('capital', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
